version: "3.8"
name: compnetwork

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: mustakimur/compnetwork:1.0
    container_name: server
    volumes:
      - ./src:/home
    networks:
      project_network:
        ipv4_address: 192.168.1.102
    stdin_open: true
    tty: true

  client1:
    image: mustakimur/compnetwork:1.0
    container_name: client1
    volumes:
      - ./src:/home
    networks:
      project_network:
        ipv4_address: 192.168.1.100
    stdin_open: true
    tty: true
    depends_on:
      - server

  client2:
    image: mustakimur/compnetwork:1.0
    container_name: client2
    volumes:
      - ./src:/home
    networks:
      project_network:
        ipv4_address: 192.168.1.101
    stdin_open: true
    tty: true
    depends_on:
      - server

networks:
  project_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
