all: BroadcastReceiver BroadcastSender

receiver:
	gcc -o BroadcastReceiver BroadcastReceiver.c

sender:
	gcc -o BroadcastSender BroadcastSender.c

clean:
	rm -f BroadcastReceiver
	rm -f BroadcastSender